### ISSUE TITLE
Usage of evolutionary tree figure allowed

### ISSUE THREAD

**Issue by tnusser** [Mooler0410/LLMsPracticalGuide#17]
Is it allowed to use the image of the LLM evolution tree in my thesis (of course with proper citation)?

**Comment by Mooler0410** [comment]
Sure!

**Comment by zl-liu** [comment]
Good evening, I would also like to use and repurpose the pptx files of the LLM evolution tree for a paper of my group. Can we gain your permission to do so (with proper citation and attribution)? Thank you for your consideration!
