### ISSUE TITLE
About Fig 1 Diag

### ISSUE THREAD

**Issue by ray-ruisun** [Mooler0410/LLMsPracticalGuide#3]
Dear authors,

        Fig 1 in the paper looks fancy, can I know which tool did you use?

Thanks,
Ray

**Comment by Mooler0410** [comment]
MS Powerpoints **+** our hands 🤪

**Comment by ahxt** [comment]
We have uploaded the source file of the gif. Thanks.

**Comment by cby-pku** [comment]
It's so amazing that you can use Powerpoints to draw such a realistic tree trunk!  Could you please share some ideas about how did you make it?
