### ISSUE TITLE
About GLM in Fig.1

### ISSUE THREAD

**Issue by Nietism** [Mooler0410/LLMsPracticalGuide#4]
In `Table 1` from the paper and `./imgs/tree.png`, GLM belongs to the **decoder-only** models, while it is catogorized into **encoder-decoder** models in the `Fig. 1` from the paper and `./imgs/survey-gif-test.gif`. What makes it different?

**Comment by Mooler0410** [comment]
Thank you for your question! Actually, the arc of GLM is  a little special, at the beginning, we put it in the decoder-only family. However, when we make the gif, we believe encoder-decoder is more suitable. But we just forgot to revise the table Lol. We'd fix it in next arxiv version. Thank you again for this!
