### ISSUE TITLE
About mimicking human in Fig. 2

### ISSUE THREAD

**Issue by hane1818** [Mooler0410/LLMsPracticalGuide#7]
Dear authors,

Our NLP application only use natural language understanding to classify user intent. Is it can be viewed as mimicking human?

Thanks.

**Comment by Mooler0410** [comment]
I believe it's a traditional NLU. You may check the Section 4.5 for some discussion about what is mimicking human.

**Comment by hane1818** [comment]
Got it! Thanks for your reply.
